
services:
  postgres:
    image: postgres:13
    container_name: database_container
    environment:
      POSTGRES_USER: AIuser
      POSTGRES_PASSWORD: AIpassword
      POSTGRES_DB: AIdb
    ports:
      - "4321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - AIEnglish-network
volumes:
  postgres-data:
networks:
  AIEnglish-network: